version: '2'

services:
  patroni1:
    build: .
    image: dingotiles/dingo-postgresql:pre-test
    container_name: patroni1
    ports: ["5432:5432", "8008:8008"]
    environment:
      # DEBUG: 1
      DINGO_CLUSTER: test-cluster
      DINGO_ORG_TOKEN: test-org-token
      DINGO_API_URI: http://${DOCKER_HOST_IP}:5000
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      DOCKER_HOST_PORT_5432: 5432
      DOCKER_HOST_PORT_8008: 8008
      BACKUPS_SUMMARY_WAITTIME: 10
    depends_on: [etcd]
    command: ["/scripts/entry.sh"]
  patroni2:
    image: dingotiles/dingo-postgresql:pre-test
    container_name: patroni2
    ports: ["5002:5432", "8002:8008"]
    environment:
      # DEBUG: 1
      DINGO_CLUSTER: test-cluster
      DINGO_ORG_TOKEN: test-org-token
      DINGO_API_URI: http://${DOCKER_HOST_IP}:5000
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      DOCKER_HOST_PORT_5432: 5002
      DOCKER_HOST_PORT_8008: 8002
      BACKUPS_SUMMARY_WAITTIME: 10
    depends_on: [etcd]
  test-api:
    # build: .
    image: dingotiles/dingo-postgresql:pre-test
    container_name: test-api
    ports: ["5000:8008"]
    environment:
      PORT: 8008
      ETCD_HOST_PORT: ${DOCKER_HOST_IP}:4001
      ETCD_PROTOCOL: http
      ETCD_USERNAME: root
      ETCD_PASSWORD: password
      AWS_ACCESS_KEY_ID: ~
      AWS_SECRET_ACCESS_KEY: ~
      WAL_S3_BUCKET: ~
      WALE_S3_ENDPOINT: ~
      WALE_S3_PREFIX: ~
    command: [/scripts/test-api.sh]
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v2.3.7
    ports: ["4001:4001", "2380:2380", "2379:2379"]
    command:
    - -name=etcd0
    - -advertise-client-urls=http://${DOCKER_HOST_IP}:2379,http://${DOCKER_HOST_IP}:4001
    - -listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
    - -initial-advertise-peer-urls=http://${DOCKER_HOST_IP}:2380
    - -listen-peer-urls=http://0.0.0.0:2380
    - -initial-cluster-token=etcd-cluster-1
    - -initial-cluster=etcd0=http://${DOCKER_HOST_IP}:2380
    - -initial-cluster-state=new

  tests:
    build: ./images/tests/
    image: dingotiles/dingo-pg-agent-container-tests
    environment:
      DOCKER_HOST_IP:
      ETCD_HOST_PORT: ${DOCKER_HOST_IP}:4001
      ETCD_PROTOCOL: http
      ETCD_USERNAME: root
      ETCD_PASSWORD: password
      PATRONI_SCOPE: test-cluster-scope
      TEST_VOLUME: /test-volume
      AWS_ACCESS_KEY_ID: ~
      AWS_SECRET_ACCESS_KEY: ~
      WAL_S3_BUCKET: ~
      AWS_REGION: ~
      APPUSER_USERNAME: appuser-username
      APPUSER_PASSWORD: appuser-password
      SUPERUSER_USERNAME: superuser-username
      SUPERUSER_PASSWORD: superuser-password
      ADMIN_PASSWORD: admin-password
