---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: agent-ci
- name: version

outputs:
- name: release-notes

run:
  path: ./agent-ci/ci/tasks/create-release-notes.sh
