---
platform: linux
image_resource:
  type: docker-image
  source: { repository: bodymindarts/delmo-concourse }

inputs:
- name: agent-ci

params:
  MACHINE_EXPORT_AWS_ACCESS_KEY_ID:
  MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY:
  MACHINE_EXPORT_AWS_REGION:
  MACHINE_EXPORT_AWS_BUCKET:
  MACHINE_NAME: dingo-postgresql-agent-pipeline

run:
  path: /entrypoint.sh
  args: [/agent-ci/tasks/delete-docker-processes.sh]
