---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bodymindarts/docker-machine-setup}


params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_BUCKET:
  AWS_INSTANCE_TYPE: t2.large
  MACHINE_NAME: dingo-postgresql-agent-pipeline
  OPEN_TCP_PORTS: 2300-6000

run:
  path: /setup-aws
