---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: agent-ci
- name: version
- name: image

outputs:
- name: dockerfile

run:
  path: agent-ci/ci/tasks/dockerfile-versioned.sh
