---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/delmo-docker-machine-setup}


params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_VPC_ID:
  AWS_SUBNET_ID:
  AWS_ZONE:
  AWS_INSTANCE_TYPE: t2.large
  AWS_SECURITY_GROUP:
  AWS_ROOT_SIZE: 40
  AWS_VOLUME_TYPE: gp2
  MACHINE_NAME: delmo-dingo-postgresql-agent-pipeline
  OPEN_TCP_PORTS: 2300-6000
  AWS_BUCKET:

run:
  path: /setup-aws
