---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: agent

outputs:
- name: generated-commitish

run:
  path: sh
  args:
  - -c
  - |
    git -C boshrelease rev-parse HEAD > generated-commitish/commitish
