---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: agent-ci
- name: agent

outputs:
- name: agent-delmo

params:
  image_name_tag: dingotiles/dingo-postgresql:pre-test

run:
  path: agent-ci/ci/tasks/prepare-delmo-docker-compose.sh
