---
platform: linux
image_resource:
  type: docker-image
  source: { repository: dingotiles/delmo-concourse }

inputs:
- name: agent-ci

params:
  MACHINE_EXPORT_AWS_ACCESS_KEY_ID:
  MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY:
  MACHINE_EXPORT_AWS_REGION:
  MACHINE_EXPORT_AWS_BUCKET:
  MACHINE_NAME: delmo-dingo-postgresql-agent-pipeline
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:
  WALE_S3_ENDPOINT:
  WAL_S3_BUCKET:
  REMOTE_HOST:
  REMOTE_PORT:
  REMOTE_USER:
  REMOTE_BASE_PATH:
  REMOTE_PRIVATE_KEY:

run:
  path: /entrypoint.sh
  args: [delmo, --only-build-task, -f, agent-ci/delmo.yml, -m, delmo-dingo-postgresql-agent-pipeline]
