---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-agent-pipeline}

inputs:
- name: agent
  path: gopath/src/github.com/dingotiles/dingo-postgresql-agent
- name: agent-ci

run:
  path: agent-ci/ci/tasks/test-agent.sh
