#!/bin/bash

set -e

if [[ -z ${TEST_DIR} ]];then
  TEST_DIR=${TEST_VOLUME}/${DELMO_TEST_NAME}
fi
mkdir -p ${TEST_DIR}

leader_name=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/leader)
leader_uri=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/members/${leader_name} | jq -r '.conn_url')

curl -s ${ETCD_HOST_PORT}/v2/keys/service/${PATRONI_SCOPE}/members?recursive=true \
  | jq -r --arg leader_uri "${leader_uri}" --arg leader_name "${leader_name}" \
  '{uris:[.node.nodes[].value | fromjson | .conn_url], leader_uri:$leader_uri, leader_name:$leader_name }' \
  | tee ${TEST_DIR}/cluster-state.json
