#!/bin/bash

set -e -u

if [[ "${ETCD_BROKER_URI:-X}" == "X" ]]; then
  etcd_cluster_uri="${ETCD_URI}/v2/keys/service/${PATRONI_SCOPE}"
else
  # Look up /service_instances/xyz for newest
  if [[ $(curl -s ${ETCD_URI}/v2/keys/service_instances | jq -r .message) == "Key not found" ]]; then
    >&2 echo "Waiting for cluster to connect to etcd..."
    exit 1
  fi
  service_instance_id=$(curl -s ${ETCD_URI}/v2/keys/service_instances | jq -r ".node.nodes | sort_by(.createdIndex) | reverse | first | .key | split(\"/\") | last")
  etcd_cluster_uri="${ETCD_URI}/v2/keys/service_instances/${service_instance_id}/service/${PATRONI_SCOPE}"
fi
echo etcd_cluster_uri: ${etcd_cluster_uri}
