#!/bin/bash

set -e -x

etcd_cluster_uri=$(/tasks/etcd_cluster_uri)

leader_name=$(curl -sk ${etcd_cluster_uri:?required}/leader | jq -r '.node.value')
leader_uri=$(curl -sk ${etcd_cluster_uri:?required}/members/${leader_name} | jq -r '.node.value' | jq -r '.conn_url')
superuser_uri=$(echo ${leader_uri} \
  | sed "s%postgres://%postgres://${SUPERUSER_USERNAME}:${SUPERUSER_PASSWORD}@%")

psql ${superuser_uri} -c "select pg_switch_xlog();"
