#!/bin/bash

etcd_cluster_uri=$(/tasks/etcd_cluster_uri)

advert=$(curl -sk ${etcd_cluster_uri}/nodes/patroni1 | jq -r '.node.value')
echo advert=${advert}

cell_guid=$(echo ${advert} | jq -r '.cell_guid')

if [[ "${cell_guid}" != "cell1" ]]; then
  echo 'patroni1 is not correctly advertizing itself'
  exit 1
fi
