#!/bin/bash

advert=$(curl -sk ${ETCD_URI:?required}/v2/keys/service/${PATRONI_SCOPE?:required}/nodes/patroni1 | jq -r '.node.value')
echo advert=${advert}

cell_guid=$(echo ${advert} | jq -r '.cell_guid')

if [[ "${cell_guid}" != "cell1" ]]; then
  echo 'patroni1 is not correctly advertizing itself'
  exit 1
fi
