#!/bin/bash

set -e -u

table_name=$1
value=$2

etcd_cluster_uri=$(/tasks/etcd_cluster_uri)

leader_name=$(curl -sk ${etcd_cluster_uri:?required}/leader | jq -r '.node.value')
leader_uri=$(curl -sk ${etcd_cluster_uri:?required}/members/${leader_name} | jq -r '.node.value' | jq -r '.conn_url')
uri=$(echo ${leader_uri} \
  | sed "s%postgres://%postgres://${APPUSER_USERNAME}:${APPUSER_PASSWORD}@%")

echo "Retrieving ${value} from ${table_name}..."

psql ${uri} -c "SELECT value FROM ${table_name};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
  exit 1
}
