#!/bin/bash

set -e

table_name=$1
value=$2

leader_name=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/leader)
leader_uri=$(etcdctl --endpoint "http://${ETCD_HOST_PORT}" get /service/${PATRONI_SCOPE}/members/${leader_name} | jq -r '.conn_url')
uri=$(echo ${leader_uri} \
  | sed "s%postgres://%postgres://${APPUSER_USERNAME}:${APPUSER_PASSWORD}@%")

echo "Storing ${value} in ${table_name}..."

psql ${uri} -c "DROP TABLE IF EXISTS ${table_name};"
psql ${uri} -c "CREATE TABLE ${table_name}(value text);"
psql ${uri} -c "INSERT INTO ${table_name} VALUES ('${value}');"
psql ${uri} -c "SELECT value FROM ${table_name};" | grep "${value}" || {
  echo Could not store and retrieve value in cluster!
  exit 1
}
