#!/bin/bash

cat <<'USAGE'
 ____  _
|  _ \(_)_ __   __ _  ___
| | | | | '_ \ / _` |/ _ \
| |_| | | | | | (_| | (_) |
|____/|_|_| |_|\__, |\___/
               |___/

Dingo PostgreSQL continuously archived from Day 1.
USAGE
