---
groups:
- name: images
  jobs: [test-agent, rc, build-image, test-image, shipit, minor, major, patch, docker-machine-setup]
- name: base-images
  jobs: [pg95-base-image]
- name: ci-image
  jobs: [build-task-image]

jobs:
- name: test-agent
  public: true
  plan:
    - {get: agent, trigger: true}
    - {get: agent-ci}
    - task: test-agent
      file: agent-ci/ci/tasks/test-agent.yml

- name: rc
  public: true
  plan:
    - {get: agent, passed: [test-agent], trigger: true}
    - {get: version, params: {pre: rc}}
    - {put: version, params: {file: version/number}}

- name: build-image
  public: true
  serial: true
  plan:
    - {get: agent-ci}
    - {get: agent, passed: [rc]}
    - {get: version, passed: [rc], trigger: true}
    - put: pg95-image
      params:
        build: agent
        cache: true
        tag: agent-ci/ci/tags/pre-test

- name: test-image
  serial_groups: [delmo]
  plan:
  - aggregate:
    - {get: agent-ci}
    - {get: agent, passed: [build-image]}
    - {get: pg95-image, passed: [build-image], trigger: true, params: {skip_download: true}}
    - {get: version, passed: [build-image]}
  - task: run-delmo-test
    file: agent-ci/ci/tasks/run-delmo-test.yml
    params:
      MACHINE_EXPORT_AWS_ACCESS_KEY_ID: {{docker-machine-access-key-id}}
      MACHINE_EXPORT_AWS_SECRET_ACCESS_KEY: {{docker-machine-secret-access-key}}
      MACHINE_EXPORT_AWS_REGION: {{docker-machine-region}}
      MACHINE_EXPORT_AWS_BUCKET: {{docker-machine-bucket}}
      AWS_ACCESS_KEY_ID: {{delmo-aws-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{delmo-aws-secret-access-key}}
      AWS_REGION: {{delmo-aws-bucket-region}}
      WALE_S3_ENDPOINT: {{delmo-aws-bucket-endpoint}}
      WAL_S3_BUCKET: {{delmo-s3-bucket}}
  - put: pg95-image
    params:
      pull_repository: dingotiles/dingo-postgresql
      pull_tag: pre-test
      cache: true
      tag: agent-ci/ci/tags/tested

- name: shipit
  public: true
  serial: true
  plan:
    - aggregate:
      - {get: agent-ci}
      - {get: agent, passed: [test-image]}
      - {get: image, resource: pg95-image, passed: [test-image], params: {skip_download: true}}
      - {get: version, passed: [test-image], params: {bump: final}}
    - task: dockerfile-versioned
      file: agent-ci/ci/tasks/dockerfile-versioned.yml
    - put: pg95-image
      params:
        build: dockerfile
        tag: version/number
        tag_prefix: v

    # - {put: version, params: {file: version/number}}

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    trigger: true
    params: {bump: patch, pre: rc}
  - put: version
    params: {file: version/number}

- name: pg95-base-image
  public: true
  serial: true
  plan:
  - {get: agent-base, trigger: true}
  - {get: agent}
  - put: pg95-base-image
    params:
      build: agent/images/postgresql95-base
      cache: true

- name: build-task-image
  public: true
  serial: true
  plan:
  - {get: agent-ci-task, trigger: true}
  - put: docker-image-ci
    params:
      build: agent-ci-task/ci/ci_image

- name: docker-machine-setup
  serial: true
  serial_groups: [delmo]
  plan:
  - get: agent-ci
  - task: docker-machine-setup
    file: agent-ci/ci/tasks/docker-machine-setup.yml
    params:
      AWS_ACCESS_KEY_ID: {{docker-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{docker-machine-secret-access-key}}
      AWS_DEFAULT_REGION: {{docker-machine-region}}
      AWS_VPC_ID: {{docker-machine-vpc-id}}
      AWS_SUBNET_ID: {{docker-machine-subnet-id}}
      AWS_ZONE: {{docker-machine-az-zone}}
      AWS_BUCKET: {{docker-machine-bucket}}
      AWS_SECURITY_GROUP: {{docker-machine-security-group}}
      AWS_AMI: ami-fd6e3bea

resources:
- name: agent
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: agent-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: agent-base
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-base]

- name: agent-ci-task
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [ci/ci_image/*]

- name: pg95-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql
    tag: latest

- name: pg95-base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql95-agent-base
    tag: latest

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql-agent-pipeline

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: version
    file: version
    private_key: {{github-private-key}}
