---
groups:
- name: images
  jobs: [rc, pg95-image, shipit, minor, major, patch]
- name: base-images
  jobs: [pg95-base-image]
- name: ci-image
  jobs: [build-task-image]

jobs:
- name: rc
  public: true
  plan:
    - {get: agent}
    - {get: version, params: {pre: rc}}
    - {put: version, params: {file: version/number}}

- name: pg95-image
  public: true
  serial: true
  plan:
    - {get: agent, trigger: true}
    - {get: version, passed: [rc], trigger: true}
    - put: pg95-image-latest
      params:
        build: agent
        cache: true

- name: shipit
  public: true
  serial: true
  plan:
    - {get: agent-ci}
    - {get: agent, passed: [pg95-image]}
    - {get: version, passed: [pg95-image], params: {bump: final}}
    - {put: version, params: {file: version/number}}

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    trigger: true
    params: {bump: patch, pre: rc}
  - put: version
    params: {file: version/number}

- name: pg95-base-image
  public: true
  serial: true
  plan:
  - {get: agent-base, trigger: true}
  - {get: agent}
  - put: pg95-base-image-latest
    params:
      build: agent/images/postgresql95-base
      cache: true

- name: build-task-image
  public: true
  serial: true
  plan:
  - {get: agent-ci-task, trigger: true}
  - put: docker-image-ci
    params:
      build: agent-ci-task/ci/ci_image


resources:
- name: agent
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: agent-ci
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}

- name: agent-base
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [images/postgresql95-base]

- name: agent-ci-task
  type: git
  source:
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
    paths: [ci/ci_image/*]

- name: pg95-image-latest
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql
    tag: latest

- name: pg95-base-image-latest
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql95-agent-base
    tag: latest

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: dingotiles/dingo-postgresql-agent-pipeline

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:dingotiles/dingo-postgresql-agent.git
    branch: version
    file: version
    private_key: {{github-private-key}}
